# version: '3'
#
# services:
#   # db:
#   #   image: postgres
#   web:
#     build: . # aqui va el dockerfile, pero al poner punto coge el de la carpeta
#      command: python manage.py runserver 0.0.0.0:8000 # cuando ejecuta el contenedor hace esto, pero lo haremos desde fuera
#     volumes:
#       - .:/code # asi editamos desde fuera el contenedor (estamos modificando nuestro contenedor)
#     ports:
#       - "8000:8000"
#     # depends_on:
#     #   - db


version: '3'

services:

  mongo:
    image: mongo:4.0
    volumes:
      - ./datos_db:/data/db
      - .:/datos

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf:/etc/nginx/conf.d:ro
      - ./cert:/etc/ssl/private:ro
      # - ./staticfiles:/usr/staticfiles
    depends_on:
      - web


  web:
    build: .
    command: gunicorn proyecto.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - mongo
    depends_on:
      - mongo
